patch_spool:
  description: "A custom service to patch spool data."
  fields:
    id:
      description: "The ID of the spool."
      example: "spool_123"
      required: true
    first_used:
      description: "The first time the spool was used."
      example: "2019-08-24T14:15:22Z"
    last_used:
      description: "The last time the spool was used."
      example: "2019-08-24T14:15:22Z"
    filament_id:
      description: "The ID of the filament used in the spool."
      example: 0
    price:
      description: "The price of the spool."
      example: 20.0
    initial_weight:
      description: "The initial weight of the spool including filament."
      example: 200.0
    spool_weight:
      description: "The weight of the empty spool."
      example: 200.0
    remaining_weight:
      description: "The remaining weight of the filament on the spool."
      example: 800.0
    used_weight:
      description: "The weight of the filament used from the spool."
      example: 200.0
    location:
      description: "The storage location of the spool."
      example: "Shelf A"
    lot_nr:
      description: "The lot number of the filament."
      example: "52342"
    comment:
      description: "Any comments about the spool."
      example: ""
    archived:
      description: "Whether the spool is archived."
      example: false
    extra:
      description: "Any extra properties for the spool."
      example:
        property1: "string"
        property2: "string"
