name: "Lint"

on:
  workflow_call:

  #pull_request:
  #  branches: ['main']
  #  paths: ['custom_components/**']

jobs:
  lint:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4"

        - name: "Set up Python"
          uses: actions/setup-python@v4.7.1
          with:
            python-version: "3.11"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Run"
          run: python3 -m ruff check .
