name: PR Tests

on:
    pull_request:
        branches: ['dev', 'main']
        paths: ['custom_components/**', 'tests/**', 'pyproject.toml', 'requirements*.txt']

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  tests:
    uses: ./.github/workflows/tests.yml
