name: Semantic Release

on:
  push:
    branches: ['main']
    # paths: ['custom_components/**']

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: montudor/action-zip@v1
      with:
        args: zip -r dist/release.zip custom-components/spoolman

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}