name: "Semantic Release"

on:
  push:
    branches: ['main']
    paths: ['custom_components/**']
    workflows: ["Validate"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm init --yes
    - run: npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec conventional-changelog-conventionalcommits --save-dev
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    # - name: Create dir
    #   run: |
    #     [ -d dist ] && echo "Directory Exists" || mkdir dist

    # - uses: montudor/action-zip@v1
    #   with:
    #     args: zip -r dist/release.zip custom_components/spoolman

    # - name: Python Semantic Release
    #   uses: python-semantic-release/python-semantic-release@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Delete dir if exists
    #   run: |
    #     [[ -d dist ]] && rm -r dist
