name: Semantic Release

on:
  push:
    branches: ['main']
    # paths: ['custom_components/**']
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm init && npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec --save-dev

    - name: Create dir
      run: |
        [ -d dist ] && echo "Directory Exists" || mkdir dist

    - uses: montudor/action-zip@v1
      with:
        args: zip -r dist/release.zip custom_components/spoolman

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete dir if exists
      run: |
        [[ -d dist ]] && rm -r dist
